#region license
// Vin
// .NET Library for Validating Vehicle Identification Numbers
// Copyright 2016 Dale Newman
//  
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//   
//       http://www.apache.org/licenses/LICENSE-2.0
//   
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#endregion

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading;

namespace DaleNewman {

    public static class Vin {

        private static readonly object LockObject = new object();

        private const int ValidVinLength = 17;
        private const int CheckDigitIndex = 8;
        // Character weights for 17 characters in VIN
        private static readonly int[] CharacterWeights = { 8, 7, 6, 5, 4, 3, 2, 10, 0, 9, 8, 7, 6, 5, 4, 3, 2 };
        private static readonly int DefaultYear = (DateTime.Now.Year / 30) * 30;
        private static readonly int NextYear = DateTime.Now.Year + 1;

        private static readonly Dictionary<char, int> Years = new Dictionary<char, int> {
            { 'A', 0 },
            { 'B', 1 },
            { 'C', 2 },
            { 'D', 3 },
            { 'E', 4 },
            { 'F', 5 },
            { 'G', 6 },
            { 'H', 7 },
            { 'J', 8 },
            { 'K', 9 },
            { 'L', 10 },
            { 'M', 11 },
            { 'N', 12 },
            { 'P', 13 },
            { 'R', 14 },
            { 'S', 15 },
            { 'T', 16 },
            { 'V', 17 },
            { 'W', 18 },
            { 'X', 19 },
            { 'Y', 20 },
            { '1', 21 },
            { '2', 22 },
            { '3', 23 },
            { '4', 24 },
            { '5', 25 },
            { '6', 26 },
            { '7', 27 },
            { '8', 28 },
            { '9', 29 }
        };

        private static readonly Dictionary<char, int> ValidCheckCharacters = new Dictionary<char, int> {
            {'0',0},
            {'1',1},
            {'2',2},
            {'3',3},
            {'4',4},
            {'5',5},
            {'6',6},
            {'7',7},
            {'8',8},
            {'9',9},
            {'X',10}
        };

        // Character transliteration, how to get from characters to numbers
        private static readonly Dictionary<char, int> CharacterTransliteration = new Dictionary<char, int> {
            {'A', 1},
            {'B', 2},
            {'C', 3},
            {'D', 4},
            {'E', 5},
            {'F', 6},
            {'G', 7},
            {'H', 8},
            {'J', 1},
            {'K', 2},
            {'L', 3},
            {'M', 4},
            {'N', 5},
            {'P', 7},
            {'R', 9},
            {'S', 2},
            {'T', 3},
            {'U', 4},
            {'V', 5},
            {'W', 6},
            {'X', 7},
            {'Y', 8},
            {'Z', 9},
            {'1', 1},
            {'2', 2},
            {'3', 3},
            {'4', 4},
            {'5', 5},
            {'6', 6},
            {'7', 7},
            {'8', 8},
            {'9', 9},
            {'0', 0}
        };

        // lock and load wmi if GetWorldManufacturer is used
        private static Dictionary<string, string> _wmi;
        private static Dictionary<string, string> WorldManufacturerIdentifiers
        {
            get
            {
                if (_wmi == null) {
                    lock (LockObject) {
                        _wmi = new Dictionary<string, string> {
{"10T", "Oshkosh"},
{"11V", "Ottawa"},
{"137", "AM General, Hummer"},
{"15G", "Gillig"},
{"177", "Thomas"},
{"17N", "John Deere"},
{"18X", "WRV"},
{"19U", "Acura"},
{"1A4", "Chrysler"},
{"1A8", "Chrysler"},
{"1AC", "AMC"},
{"1AM", "AMC"},
{"1B3", "Dodge"},
{"1B4", "Dodge"},
{"1B6", "Dodge"},
{"1B7", "Dodge"},
{"1BA", "Blue Bird"},
{"1BB", "Blue Bird"},
{"1BD", "Blue Bird"},
{"1C3", "Chrysler"},
{"1C4", "Chrysler"},
{"1C6", "Chrysler"},
{"1C8", "Chrysler"},
{"1C9", "Chance"},
{"1CY", "Crane Carrier"},
{"1D3", "Dodge"},
{"1D4", "Dodge"},
{"1D5", "Dodge"},
{"1D7", "Dodge"},
{"1D8", "Dodge"},
{"1EC", "Fleetwood"},
{"1F1", "Ford"},
{"1F6", "Ford"},
{"1F9", "FWD Corp."},
{"1FA", "Ford Motor Company"},
{"1FB", "Ford Motor Company"},
{"1FC", "Ford Motor Company"},
{"1FD", "Ford Motor Company"},
{"1FE", "Ford Moter Company"},
{"1FM", "Ford Motor Company"},
{"1FT", "Ford Motor Company"},
{"1FU", "Freightliner"},
{"1FV", "Freightliner"},
{"1G", "General Motors USA"},
{"1G1", "Chevrolet USA"},
{"1G2", "Pontiac USA"},
{"1G3", "Oldsmobile USA"},
{"1G4", "Buick USA"},
{"1G5", "GMC, Pontiac"},
{"1G6", "Cadillac USA"},
{"1G8", "Saturn USA"},
{"1GA", "Chevrolet"},
{"1GB", "Chevrolet"},
{"1GC", "Chevrolet Truck USA"},
{"1GD", "GMC"},
{"1GE", "Cadillac"},
{"1GF", "Flexible"},
{"1GG", "Isuzu"},
{"1GH", "GMC, Oldsmobile"},
{"1GJ", "GMC"},
{"1GK", "GMC"},
{"1GM", "Pontiac USA"},
{"1GN", "Chevrolet"},
{"1GT", "GMC Truck USA"},
{"1GY", "Cadillac USA"},
{"1H", "Honda USA"},
{"1HD", "Harley-Davidson"},
{"1HG", "Honda"},
{"1HS", "International"},
{"1HT", "International"},
{"1HV", "International"},
{"1J4", "Jeep"},
{"1J7", "Jeep"},
{"1J8", "Jeep"},
{"1JC", "AMC, Jeep"},
{"1JD", "AMC"},
{"1JT", "AMC, Jeep"},
{"1L", "Lincoln USA"},
{"1L1", "Lincoln"},
{"1LN", "Lincoln"},
{"1M1", "Mack Truck USA"},
{"1M2", "Mack Truck USA"},
{"1M3", "Mack Truck USA"},
{"1M4", "Mack Truck USA"},
{"1M8", "MCI"},
{"1M9", "Mynatt Truck & Equipment"},
{"1ME", "Mercury USA"},
{"1MR", "Lincoln"},
{"1N", "Nissan USA"},
{"1N4", "Nissan"},
{"1N6", "Datsun, Nissan"},
{"1N9", "Neoplan"},
{"1NK", "Kenworth"},
{"1NP", "Peterbilt"},
{"1NX", "NUMMI USA"},
{"1P3", "Plymouth USA"},
{"1P4", "Plymouth"},
{"1P7", "Plymouth"},
{"1P9", "Panoz"},
{"1R9", "Roadrunner Hay Squeeze USA"},
{"1RF", "Roadmaster"},
{"1S9", "Saleen"},
{"1T8", "Thomas"},
{"1TU", "TMC"},
{"1V1", "Volkswagen"},
{"1VW", "Volkswagen USA"},
{"1WA", "Autostar"},
{"1WB", "Autostar"},
{"1WU", "White Volvo"},
{"1WV", "Winnebago"},
{"1XK", "Kenworth USA"},
{"1XM", "AMC"},
{"1XP", "Peterbilt USA"},
{"1Y1", "Chevrolet, Geo"},
{"1YV", "Mazda USA (AutoAlliance International)"},
{"1Z3", "Mitsubishi"},
{"1Z5", "Mitsubishi"},
{"1Z7", "Mitsubishi"},
{"1ZV", "Ford (AutoAlliance International)"},
{"1ZW", "Mercury"},
{"2A3", "Chrysler"},
{"2A4", "Chrysler Canada"},
{"2A8", "Chrysler"},
{"2B1", "Orion"},
{"2B3", "Dodge Canada"},
{"2B4", "Dodge Canada"},
{"2B5", "Dodge Canada"},
{"2B6", "Dodge Canada"},
{"2B7", "Dodge Canada"},
{"2B8", "Dodge Canada"},
{"2BC", "AMC, Jeep"},
{"2C1", "Chevrolet, Geo"},
{"2C3", "Chrysler Canada"},
{"2C4", "Chrysler"},
{"2C7", "Pontiac"},
{"2C8", "Chrysler"},
{"2CC", "AMC, Eagle"},
{"2CK", "Geo, Pontiac"},
{"2CM", "AMC"},
{"2CN", "CAMI"},
{"2D3", "Dodge Canada"},
{"2D4", "Dodge Canada"},
{"2D6", "Dodge Canada"},
{"2D7", "Dodge Canada"},
{"2D8", "Dodge Canada"},
{"2E3", "Eagle"},
{"2FA", "Ford Motor Company Canada"},
{"2FB", "Ford Motor Company Canada"},
{"2FC", "Ford Motor Company Canada"},
{"2FD", "Ford Motor Company Canada"},
{"2FM", "Ford Motor Company Canada"},
{"2FT", "Ford Motor Company Canada"},
{"2FU", "Freightliner"},
{"2FV", "Freightliner"},
{"2FW", "Sterling"},
{"2FZ", "Sterling"},
{"2G", "General Motors Canada"},
{"2G0", "GMC"},
{"2G1", "Chevrolet Canada"},
{"2G2", "Pontiac Canada"},
{"2G3", "Oldsmobile Canada"},
{"2G4", "Buick Canada"},
{"2G5", "GMC"},
{"2G7", "Pontiac"},
{"2G8", "Chevrolet"},
{"2GA", "Chevrolet"},
{"2GB", "Chevrolet"},
{"2GD", "GMC"},
{"2GJ", "GMC"},
{"2GK", "GMC"},
{"2GN", "Chevrolet"},
{"2GT", "GMC"},
{"2HG", "Honda Canada"},
{"2HH", "Acura"},
{"2HJ", "Honda Canada"},
{"2HK", "Honda Canada"},
{"2HM", "Hyundai Canada"},
{"2HN", "Acura"},
{"2HS", "International"},
{"2HT", "International"},
{"2J4", "Jeep"},
{"2LM", "Lincoln"},
{"2M", "Mercury"},
{"2M2", "Mack"},
{"2ME", "Mercury"},
{"2MH", "Mercury"},
{"2MR", "Mercury"},
{"2NK", "Kenworth"},
{"2NP", "Peterbilt"},
{"2NV", "Nova Bus Canada"},
{"2P3", "Plymouth Canada"},
{"2P4", "Plymouth"},
{"2P5", "Plymouth"},
{"2P9", "Prevost"},
{"2PC", "Prevost"},
{"2S2", "Suzuki"},
{"2S3", "Suzuki"},
{"2T", "Toyota Canada"},
{"2T1", "Toyota"},
{"2T2", "Lexus"},
{"2V4", "Volkswagen Canada"},
{"2V8", "Volkswagen Canada"},
{"2WK", "Western Star Trucks"},
{"2WL", "Western Star Trucks"},
{"2WM", "Western Star"},
{"2XK", "Kenworth"},
{"2XM", "Eagle"},
{"2XP", "Peterbilt"},
{"3A4", "Chrysler"},
{"3A8", "Chrysler"},
{"3AB", "Dina"},
{"3AL", "Freightliner"},
{"3B3", "Dodge"},
{"3B4", "Dodge"},
{"3B6", "Dodge"},
{"3B7", "Dodge"},
{"3BK", "Kenworth"},
{"3BP", "Peterbilt"},
{"3C3", "Chrysler Mexico"},
{"3C4", "Chrysler Mexico"},
{"3C8", "Chrysler Mexico"},
{"3CA", "Chrysler Mexico"},
{"3D3", "Dodge Mexico"},
{"3D5", "Dodge Mexico"},
{"3D6", "Dodge Mexico"},
{"3D7", "Dodge Mexico"},
{"3FA", "Ford Motor Company Mexico"},
{"3FC", "Ford"},
{"3FD", "Ford"},
{"3FE", "Ford Motor Company Mexico"},
{"3FR", "Ford"},
{"3FT", "Ford"},
{"3G", "General Motors Mexico"},
{"3G1", "Chevrolet"},
{"3G2", "Pontiac"},
{"3G4", "Buick"},
{"3G5", "Buick"},
{"3G7", "Pontiac"},
{"3GB", "Chevrolet"},
{"3GC", "Chevrolet"},
{"3GD", "GMC"},
{"3GE", "Chevrolet"},
{"3GK", "GMC"},
{"3GN", "Chevrolet"},
{"3GT", "GMC"},
{"3GY", "Cadillac"},
{"3H", "Honda Mexico"},
{"3HA", "International"},
{"3HG", "Honda"},
{"3HM", "Honda"},
{"3HS", "International"},
{"3HT", "International"},
{"3JB", "BRP Mexico (all-terrain vehicles)"},
{"3LN", "Lincoln"},
{"3MA", "Mercury"},
{"3ME", "Mercury"},
{"3MZ", "Mazda Mexico"},
{"3N", "Nissan Mexico"},
{"3N1", "Nissan"},
{"3NK", "Kenworth"},
{"3NM", "Peterbilt"},
{"3P3", "Plymouth Mexico"},
{"3TM", "Toyota"},
{"3VW", "Volkswagen Mexico"},
{"3WK", "Kenworth"},
{"45V", "Utilimaster"},
{"46G", "Gillig"},
{"49H", "Sterling"},
{"4A3", "Mitsubishi"},
{"4A4", "Mitsubishi"},
{"4B3", "Dodge"},
{"4C3", "Chrysler"},
{"4CD", "Oshkosh"},
{"4DR", "Genesis, International"},
{"4E3", "Eagle"},
{"4F", "Mazda USA"},
{"4F2", "Mazda"},
{"4F4", "Mazda"},
{"4G1", "Chevrolet"},
{"4G2", "Pontiac"},
{"4GD", "GMC"},
{"4GT", "Isuzu, WhiteGMC"},
{"4JG", "Mercedes-Benz USA"},
{"4KB", "Chevrolet"},
{"4KD", "GMC"},
{"4KL", "Isuzu"},
{"4M", "Mercury"},
{"4M2", "Mercury"},
{"4N1", "Nissan"},
{"4N2", "Nissan"},
{"4NU", "Isuzu"},
{"4P3", "Plymouth"},
{"4RK", "Nova Bus USA"},
{"4S", "Subaru-Isuzu Automotive"},
{"4S1", "Isuzu"},
{"4S2", "Isuzu"},
{"4S3", "Subaru"},
{"4S4", "Subaru"},
{"4S6", "Honda"},
{"4S7", "Spartan"},
{"4SL", "Magnum"},
{"4T", "Toyota"},
{"4T1", "Toyota"},
{"4T3", "Toyota"},
{"4T9", "Lumen Motors (zero-emission mid-engined car)"},
{"4TA", "Toyota"},
{"4UF", "Arctic Cat Inc."},
{"4US", "BMW USA"},
{"4UZ", "Freightliner"},
{"4V1", "Volvo"},
{"4V2", "Volvo"},
{"4V3", "Volvo"},
{"4V4", "Volvo"},
{"4V5", "Volvo"},
{"4V6", "Volvo"},
{"4VA", "Volvo"},
{"4VG", "Volvo"},
{"4VH", "Volvo"},
{"4VL", "Volvo"},
{"4VM", "Volvo"},
{"4VZ", "Volvo"},
{"538", "Zero Motorcycles (USA)"},
{"5AS", "GEM"},
{"5B4", "Workhorse"},
{"5CK", "Western Star Trucks"},
{"5F", "Honda USA-Alabama"},
{"5FN", "Honda"},
{"5FY", "New Flyer"},
{"5GA", "Buick"},
{"5GR", "Hummer"},
{"5GT", "Hummer"},
{"5GZ", "Saturn"},
{"5J6", "Honda"},
{"5J8", "Acura"},
{"5KJ", "Western Star Trucks"},
{"5KK", "Western Star Trucks"},
{"5L", "Lincoln"},
{"5LM", "Lincoln"},
{"5LT", "Lincoln"},
{"5N1", "Nissan USA"},
{"5N3", "Infiniti"},
{"5NM", "Hyundai"},
{"5NP", "Hyundai USA"},
{"5PV", "Hino"},
{"5S3", "Saab"},
{"5SX", "Amercian LeFrance"},
{"5T", "Toyota USA - trucks"},
{"5T4", "Workhorse"},
{"5TB", "Toyota"},
{"5TD", "Toyota"},
{"5TE", "Toyota"},
{"5TF", "Toyota"},
{"5UM", "BMW"},
{"5UX", "BMW"},
{"5Y2", "Pontiac"},
{"5YJ", "Tesla Motors"},
{"6AB", "MAN Australia"},
{"6F4", "Nissan Motor Company Australia"},
{"6F5", "Kenworth Australia"},
{"6FP", "Ford Motor Company Australia"},
{"6G1", "General Motors-Holden (post Nov 2002)"},
{"6G2", "Pontiac Australia (GTO & G8)"},
{"6H8", "General Motors-Holden (pre Nov 2002)"},
{"6MM", "Mitsubishi Motors Australia"},
{"6MP", "Mercury"},
{"6T1", "Toyota Motor Corporation Australia"},
{"6U9", "Privately Imported car in Australia"},
{"8A1", "Renault Argentina"},
{"8AD", "Peugeot Argentina"},
{"8AF", "Ford Motor Company Argentina"},
{"8AG", "Chevrolet Argentina"},
{"8AJ", "Toyota Argentina"},
{"8AK", "Suzuki Argentina"},
{"8AP", "Fiat Argentina"},
{"8AW", "Volkswagen Argentina"},
{"8GD", "Peugeot Chile"},
{"8GG", "Chevrolet Chile"},
{"935", "Citroën Brazil"},
{"936", "Peugeot Brazil"},
{"93H", "Honda Brazil"},
{"93R", "Toyota Brazil"},
{"93U", "Audi Brazil"},
{"93V", "Audi Brazil"},
{"93X", "Mitsubishi Motors Brazil"},
{"93Y", "Renault Brazil"},
{"94D", "Nissan Brazil"},
{"9BD", "Fiat Brazil"},
{"9BF", "Ford Motor Company Brazil"},
{"9BG", "Chevrolet Brazil"},
{"9BM", "Mercedes-Benz Brazil"},
{"9BR", "Toyota Brazil"},
{"9BS", "Scania Brazil"},
{"9BW", "Volkswagen Brazil"},
{"9DW", "Volkswagen"},
{"9FB", "Renault Colombia"},
{"AAV", "Volkswagen South Africa"},
{"AC5", "Hyundai South Africa"},
{"ADD", "Hyundai South Africa"},
{"AFA", "Ford South Africa"},
{"AHT", "Toyota South Africa"},
{"J81", "Chevrolet,Geo"},
{"J87", "Isuzu"},
{"J8B", "Chevrolet"},
{"J8D", "GMC"},
{"J8Z", "Chevrolet"},
{"JA", "Isuzu"},
{"JA3", "Mitsubishi"},
{"JA4", "Mitsubishi"},
{"JA7", "Mitsubishi"},
{"JAA", "Isuzu"},
{"JAB", "Isuzu"},
{"JAC", "Isuzu"},
{"JAE", "Acura"},
{"JAL", "Isuzu"},
{"JB3", "Dodge"},
{"JB4", "Dodge"},
{"JB7", "Dodge"},
{"JC2", "Ford"},
{"JD", "Daihatsu"},
{"JD1", "Daihatsu"},
{"JD2", "Daihatsu"},
{"JE3", "Eagle"},
{"JF", "Fuji Heavy Industries (Subaru)"},
{"JF1", "Subaru"},
{"JF2", "Subaru"},
{"JF3", "Subaru"},
{"JF4", "Saab"},
{"JG1", "Chevrolet, Geo"},
{"JG7", "Pontiac"},
{"JGC", "Geo"},
{"JH", "Honda"},
{"JH4", "Acura"},
{"JHB", "Hino"},
{"JHL", "Honda"},
{"JHM", "Honda"},
{"JJ3", "Chrysler"},
{"JK", "Kawasaki (motorcycles)"},
{"JL5", "Mitsubishi Fuso"},
{"JL6", "Mitsubishi"},
{"JLS", "Sterling"},
{"JM1", "Mazda"},
{"JM2", "Mazda"},
{"JM3", "Mazda"},
{"JMB", "Mitsubishi Motors"},
{"JMY", "Mitsubishi Motors"},
{"JMZ", "Mazda"},
{"JN", "Nissan"},
{"JN1", "Datsun, Nissan"},
{"JN3", "Nissan"},
{"JN4", "Nissan"},
{"JN6", "Datsun, Nissan"},
{"JN8", "Nissan"},
{"JNA", "Nissan"},
{"JNK", "Infiniti"},
{"JNR", "Infiniti"},
{"JNX", "Infiniti"},
{"JP3", "Plymouth"},
{"JP4", "Plymouth"},
{"JP7", "Plymouth"},
{"JR2", "Isuzu"},
{"JS", "Suzuki"},
{"JS2", "Suzuki"},
{"JS3", "Suzuki"},
{"JS4", "Suzuki"},
{"JT", "Toyota"},
{"JT2", "Toyota"},
{"JT3", "Toyota"},
{"JT4", "Toyota"},
{"JT5", "Toyota"},
{"JT6", "Lexus"},
{"JT8", "Lexus"},
{"JTD", "Toyota"},
{"JTE", "Toyota"},
{"JTH", "Lexus"},
{"JTJ", "Lexus"},
{"JTK", "Scion"},
{"JTL", "Scion"},
{"JTM", "Toyota"},
{"JTN", "Toyota"},
{"JW6", "Mitsubishi"},
{"JW7", "Mitsubishi"},
{"JY", "Yamaha (motorcycles)"},
{"KL", "Daewoo General Motors South Korea"},
{"KL1", "Chevrolet"},
{"KL2", "Pontiac"},
{"KL5", "Suzuki"},
{"KL7", "Asuna"},
{"KLA", "Daewoo"},
{"KM", "Hyundai"},
{"KM1", "Hyosung (motorcycles)"},
{"KM8", "Hyundai"},
{"KMF", "Hyundai"},
{"KMH", "Hyundai"},
{"KMY", "Daelim (motorcycles)"},
{"KN", "Kia"},
{"KNA", "Kia"},
{"KND", "Hyundai, Kia"},
{"KNJ", "Ford"},
{"KNM", "Renault Samsung"},
{"KPA", "SsangYong"},
{"KPH", "Mitsubishi"},
{"KPT", "SsangYong"},
{"L4B", "Xingyue Group (motorcycles)"},
{"L5C", "KangDi (ATV)"},
{"L5K", "Zhejiang Yongkang Easy Vehicle"},
{"L5N", "Zhejiang Taotao, China (ATV & motorcycles)"},
{"L5Y", "Merato Motorcycle Taizhou Zhongneng"},
{"L85", "Zhejiang Yongkang Huabao Electric Appliance"},
{"L8X", "Zhejiang Summit Huawin Motorcycle"},
{"LAN", "Changzhou Yamasaki Motorcycle"},
{"LB2", "Geely Motorcycles"},
{"LBB", "Zhejiang Qianjiang Motorcycle (Keeway/Generic)"},
{"LBE", "Beijing Hyundai"},
{"LBM", "Zongshen Piaggio"},
{"LBP", "Chongqing Jainshe Yamaha (motorcycles)"},
{"LCE", "Hangzhou Chunfeng Motorcycles (CFMOTO)"},
{"LDC", "Dong Feng Peugeot Citroen (DPCA), China"},
{"LDD", "Dandong Huanghai Automobile"},
{"LDN", "SouEast Motor"},
{"LDY", "Zhongtong Coach, China"},
{"LE4", "Beijing Benz, China"},
{"LES", "Isuzu"},
{"LET", "Jiangling-Isuzu Motors, China"},
{"LFB", "FAW, China (busses)"},
{"LFG", "Taizhou Chuanl Motorcycle Manufacturing"},
{"LFP", "FAW, China (passenger vehicles)"},
{"LFT", "FAW, China (trailers)"},
{"LFV", "FAW-Volkswagen, China"},
{"LFW", "FAW JieFang, China"},
{"LFY", "Changshu Light Motorcycle Factory"},
{"LGB", "Dong Feng (DFM), China"},
{"LGH", "Qoros (formerly Dong Feng (DFM)), China"},
{"LGX", "BYD Auto, China"},
{"LH1", "FAW-Haima, China"},
{"LHB", "Beijing Automotive Industry Holding"},
{"LJ1", "JAC, China"},
{"LJC", "JAC, China"},
{"LKL", "Suzhou King Long, China"},
{"LL6", "Hunan Changfeng Manufacture Joint-Stock"},
{"LL8", "Linhai (ATV)"},
{"LM5", "Isuzu"},
{"LMC", "Suzuki Hong Kong (motorcycles)"},
{"LPR", "Yamaha Hong Kong (motorcycles)"},
{"LSG", "Shanghai General Motors, China"},
{"LSJ", "MG Motor UK Limited - SAIC Motor, Shanghai, China"},
{"LSV", "Shanghai Volkswagen, China"},
{"LSY", "Brilliance Zhonghua"},
{"LTV", "Toyota Tian Jin"},
{"LUC", "Guangqi Honda, China"},
{"LVS", "Ford Chang An"},
{"LVV", "Chery, China"},
{"LVZ", "Dong Feng Sokon Motor Company (DFSK)"},
{"LZE", "Isuzu Guangzhou, China"},
{"LZG", "Shaanxi Automobile Group, China"},
{"LZM", "MAN China"},
{"LZP", "Zhongshan Guochi Motorcycle (Baotian)"},
{"LZY", "Yutong Zhengzhou, China"},
{"LZZ", "Chongqing Shuangzing Mech & Elec (Howo)"},
{"MA1", "Mahindra & Mahindra"},
{"MA3", "Suzuki India (Maruti)"},
{"MA6", "GM India"},
{"MA7", "Mitsubishi India (formerly Honda)"},
{"MAB", "Mahindra & Mahindra"},
{"MAC", "Mahindra & Mahindra"},
{"MAJ", "Ford India"},
{"MAK", "Honda Siel Cars India"},
{"MAL", "Hyundai"},
{"MAT", "Tata Motors"},
{"MB1", "Ashok Leyland"},
{"MBH", "Suzuki India (Maruti)"},
{"MBJ", "Toyota India"},
{"MBR", "Mercedes-Benz India"},
{"MC2", "Volvo Eicher commercial vehicles limited."},
{"MCA", "Fiat India"},
{"MCB", "GM India"},
{"MD2", "Bajaj Auto"},
{"MDH", "Nissan India"},
{"MEE", "Renault India"},
{"MEX", "Volkswagen India"},
{"MHF", "Toyota Indonesia"},
{"MHR", "Honda Indonesia"},
{"ML3", "Dodge"},
{"MLC", "Suzuki Thailand"},
{"MLH", "Honda Thailand"},
{"MM8", "Mazda Thailand"},
{"MMB", "Mitsubishi Thailand"},
{"MMC", "Mitsubishi Thailand"},
{"MMM", "Chevrolet Thailand"},
{"MMT", "Mitsubishi Thailand"},
{"MNB", "Ford Thailand"},
{"MNT", "Nissan Thailand"},
{"MP1", "Isuzu Thailand"},
{"MPA", "Isuzu Thailand"},
{"MR0", "Toyota Thailand"},
{"MRH", "Honda Thailand"},
{"NLA", "Honda Türkiye"},
{"NLE", "Mercedes-Benz Türk Truck"},
{"NLH", "Hyundai Assan"},
{"NM0", "Ford Turkey"},
{"NM4", "Tofaş Türk"},
{"NMT", "Toyota Türkiye"},
{"PE1", "Ford Phillipines"},
{"PE3", "Mazda Phillipines"},
{"PL1", "Proton, Malaysia"},
{"PNA", "NAZA, Malaysia (Peugeot)"},
{"RF3", "Aeon Motor, Taiwan"},
{"RFB", "Kymco, Taiwan"},
{"RFG", "Sanyang SYM, Taiwan"},
{"RFL", "Adly, Taiwan"},
{"RFT", "CPI, Taiwan"},
{"SA9", "Morgan"},
{"SAJ", "Jaguar"},
{"SAL", "Land Rover"},
{"SAR", "Rover"},
{"SAT", "Triumph"},
{"SAX", "Sterling"},
{"SB1", "Toyota UK"},
{"SBM", "McLaren"},
{"SCA", "Rolls Royce"},
{"SCB", "Bentley"},
{"SCC", "Lotus Cars"},
{"SCE", "DeLorean Motor Cars N. Ireland (UK)"},
{"SCF", "Aston Martin"},
{"SDB", "Peugeot UK (formerly Talbot)"},
{"SDL", "TVR Engineering"},
{"SED", "General Motors Luton Plant"},
{"SEY", "LDV"},
{"SFA", "Ford UK"},
{"SFD", "Alexander Dennis UK"},
{"SHH", "Honda UK"},
{"SHS", "Honda UK"},
{"SJN", "Nissan UK"},
{"SKF", "Vauxhall"},
{"SLP", "JCB Research UK"},
{"SMT", "Triumph Motorcycles"},
{"SUF", "Fiat Auto Poland"},
{"SUL", "FSC (Poland)"},
{"SUP", "FSO-Daewoo (Poland)"},
{"SUU", "Solaris Bus & Coach (Poland)"},
{"TCC", "Micro Compact Car AG (smart 1998-1999)"},
{"TDM", "QUANTYA Swiss Electric Movement (Switzerland)"},
{"TM9", "Škoda trolleybuses (Czech Republic)"},
{"TMA", "Hyundai Motor Manufacturing Czech"},
{"TMB", "Škoda (Czech Republic)"},
{"TMK", "Karosa (Czech Republic)"},
{"TMP", "Škoda trolleybuses (Czech Republic)"},
{"TMT", "Tatra (Czech Republic)"},
{"TN9", "Karosa (Czech Republic)"},
{"TNE", "TAZ"},
{"TRA", "Ikarus Bus"},
{"TRU", "Audi Hungary"},
{"TSE", "Ikarus Egyedi Autobuszgyar, (Hungary)"},
{"TSM", "Suzuki Hungary"},
{"TW1", "Toyota Caetano Portugal"},
{"TYA", "Mitsubishi Trucks Portugal"},
{"TYB", "Mitsubishi Trucks Portugal"},
{"U5Y", "Kia Motors Slovakia"},
{"U6Y", "Kia Motors Slovakia"},
{"UU1", "Renault Dacia, (Romania)"},
{"UU3", "ARO"},
{"UU6", "Daewoo Romania"},
{"VAG", "Magna Steyr Puch"},
{"VAN", "MAN Austria"},
{"VBK", "KTM (Motorcycles)"},
{"VF1", "Renault"},
{"VF2", "Renault"},
{"VF3", "Peugeot"},
{"VF4", "Talbot"},
{"VF6", "Renault (Trucks & Buses)"},
{"VF7", "Citroën"},
{"VF8", "Matra"},
{"VG5", "MBK (motorcycles)"},
{"VG6", "Mack"},
{"VLU", "Scania France"},
{"VN1", "SOVAB (France)"},
{"VNE", "Irisbus (France)"},
{"VNK", "Toyota France"},
{"VNV", "Renault-Nissan"},
{"VS6", "Ford Spain"},
{"VS7", "Citroën Spain"},
{"VS9", "Carrocerias Ayats (Spain)"},
{"VSA", "Mercedes-Benz Spain"},
{"VSE", "Suzuki Spain (Santana Motors)"},
{"VSK", "Nissan Spain"},
{"VSS", "Seat"},
{"VSX", "Opel Spain"},
{"VTH", "Derbi (motorcycles)"},
{"VTT", "Suzuki Spain (motorcycles)"},
{"VV9", "TAURO Spain"},
{"VWA", "Nissan Spain"},
{"VWV", "Volkswagen Spain"},
{"VX1", "Zastava / Yugo Serbia"},
{"W06", "Cadillac"},
{"W0L", "Opel"},
{"WA1", "Audi SUV"},
{"WAG", "Neoplan"},
{"WAU", "Audi"},
{"WBA", "BMW"},
{"WBS", "BMW"},
{"WBX", "BMW"},
{"WD0", "Dodge"},
{"WD1", "Dodge"},
{"WD2", "Dodge"},
{"WD5", "Dodge"},
{"WD8", "Dodge"},
{"WDA", "Daimler"},
{"WDB", "Maybach, Mercedes-Benz"},
{"WDC", "Mercedes-Benz"},
{"WDD", "Mercedes-Benz"},
{"WDF", "Mercedes-Benz (commercial vehicles)"},
{"WDP", "Dodge"},
{"WDX", "Dodge"},
{"WDY", "Dodge"},
{"WEB", "Evobus GmbH (Mercedes-Bus)"},
{"WF0", "Ford Germany"},
{"WF1", "Merkur"},
{"WJM", "Iveco Magirus"},
{"WKK", "Fahrzeugwerke"},
{"WMA", "MAN Germany"},
{"WME", "Mercedes-Benz"},
{"WMW", "Mini"},
{"WMX", "Mercedes-AMG"},
{"WP0", "Porsche"},
{"WP1", "Porsche SUV"},
{"WUA", "Audi"},
{"WV1", "Volkswagen Commercial Vehicles"},
{"WV2", "Volkswagen Bus/Van"},
{"WV3", "Volkswagen Trucks"},
{"WVG", "Volkswagen MPV/SUV"},
{"WVW", "Volkswagen"},
{"X4X", "AvtoTor (Russia, BMW SKD)"},
{"X7L", "Renault AvtoFramos (Russia)"},
{"X7M", "Hyundai TagAZ (Russia)"},
{"XLB", "Volvo (NedCar)"},
{"XLE", "Scania Netherlands"},
{"XLR", "DAF (trucks)"},
{"XMC", "Mitsubishi (NedCar)"},
{"XTA", "Lada/AutoVaz (Russia)"},
{"XTT", "UAZ/Sollers (Russia)"},
{"XUF", "General Motors Russia"},
{"XUU", "AvtoTor (Russia, General Motors SKD)"},
{"XW8", "Volkswagen Group Russia"},
{"XWB", "UZ-Daewoo (Uzbekistan)"},
{"XWE", "AvtoTor (Russia, Hyundai-Kia SKD)"},
{"Y6D", "Zaporozhets/AvtoZAZ (Ukraine)"},
{"YB3", "Volvo"},
{"YBW", "Volkswagen Belgium"},
{"YCM", "Mazda Belgium"},
{"YE2", "Van Hool (buses)"},
{"YK1", "Saab-Valmet Finland"},
{"YS2", "Scania AB"},
{"YS3", "Saab"},
{"YS4", "Scania Bus"},
{"YTN", "Saab NEVS"},
{"YU7", "Husaberg (motorcycles)"},
{"YV1", "Volvo Cars"},
{"YV2", "Volvo Trucks"},
{"YV3", "Volvo Buses"},
{"YV4", "Volvo Cars"},
{"YV5", "Volvo"},
{"Z8M", "Marussia (Russia)"},
{"ZA9", "Lamborghini"},
{"ZAA", "Autobianchi"},
{"ZAM", "Maserati"},
{"ZAP", "Piaggio/Vespa/Gilera"},
{"ZAR", "Alfa Romeo"},
{"ZBN", "Benelli"},
{"ZC2", "Chrysler"},
{"ZCF", "Iveco"},
{"ZCG", "Cagiva SpA / MV Agusta"},
{"ZD0", "Yamaha Italy"},
{"ZD3", "Beta Motor"},
{"ZD4", "Aprilia"},
{"ZDF", "Ferrari Dino"},
{"ZDM", "Ducati Motor Holdings SpA"},
{"ZFA", "Fiat"},
{"ZFC", "Fiat V.I."},
{"ZFF", "Ferrari"},
{"ZGU", "Moto Guzzi"},
{"ZHW", "Lamborghini"},
{"ZJM", "Malaguti"},
{"ZJN", "Innocenti"},
{"ZKH", "Husqvarna Motorcycles Italy"},
{"ZLA", "Lancia"},
{"ZOM", "OM"}
                        };

                    }
                }
                return _wmi;
            }
        }

        public static bool IsValid(string vin) {

            var value = 0;

            if (vin?.Length != ValidVinLength) {
                return false;
            }

            var checkCharacter = vin[CheckDigitIndex];
            if (!ValidCheckCharacters.ContainsKey(checkCharacter)) {
                return false;
            }

            for (var i = 0; i < ValidVinLength; i++) {
                if (!CharacterTransliteration.ContainsKey(vin[i])) {
                    return false;
                }
                value += (CharacterWeights[i] * (CharacterTransliteration[vin[i]]));
            }

            return (value % 11) == ValidCheckCharacters[checkCharacter];
        }

        public static string GetWorldManufacturer(string vinOrWmi) {
            if (string.IsNullOrEmpty(vinOrWmi))
                return string.Empty;

            if (vinOrWmi.Length < 2)
                return string.Empty;

            if (vinOrWmi.Length > 2 && WorldManufacturerIdentifiers.ContainsKey(vinOrWmi.Substring(0, 3))) {
                return WorldManufacturerIdentifiers[vinOrWmi.Substring(0, 3)];
            }

            return WorldManufacturerIdentifiers.ContainsKey(vinOrWmi.Substring(0, 2)) ? WorldManufacturerIdentifiers[vinOrWmi.Substring(0, 2)] : string.Empty;
        }

        public static int GetModelYear(char yearCharacter, int startYear = 0) {
            if (startYear == 0) {
                startYear = DefaultYear;
            }

            if (Years.ContainsKey(yearCharacter)) {
                var year = startYear + Years[yearCharacter];
                if (year > NextYear) {
                    year -= 30;
                }
                return year;
            }

            return 0;

        }

        public static int GetModelYear(string vin, int startYear = 0) {

            if (string.IsNullOrEmpty(vin))
                return 0;

            if (vin.Length < 10) {
                return 0;
            }

            var yearCharacter = vin[9];

            return GetModelYear(yearCharacter, startYear);
        }

    }
}
